// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCH4b3S-wQcftGVkhmG6alcsXEA17JIM',
    appId: '1:111720929749:web:0805a2e25248a3235e055c',
    messagingSenderId: '111720929749',
    projectId: 'socchat-d20de',
    authDomain: 'socchat-d20de.firebaseapp.com',
    storageBucket: 'socchat-d20de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhg8mb0BYGs3qM4cuqGZOybkhiz5qnJE',
    appId: '1:111720929749:android:7a2480d183ac28c45e055c',
    messagingSenderId: '111720929749',
    projectId: 'socchat-d20de',
    storageBucket: 'socchat-d20de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLs9XYbJGfdFjgDVsuvzEGlu_NXU3Lxqo',
    appId: '1:111720929749:ios:5627c5747ecb613b5e055c',
    messagingSenderId: '111720929749',
    projectId: 'socchat-d20de',
    storageBucket: 'socchat-d20de.firebasestorage.app',
    iosBundleId: 'com.example.socchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLs9XYbJGfdFjgDVsuvzEGlu_NXU3Lxqo',
    appId: '1:111720929749:ios:5627c5747ecb613b5e055c',
    messagingSenderId: '111720929749',
    projectId: 'socchat-d20de',
    storageBucket: 'socchat-d20de.firebasestorage.app',
    iosBundleId: 'com.example.socchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtCH4b3S-wQcftGVkhmG6alcsXEA17JIM',
    appId: '1:111720929749:web:fca6bad00353963b5e055c',
    messagingSenderId: '111720929749',
    projectId: 'socchat-d20de',
    authDomain: 'socchat-d20de.firebaseapp.com',
    storageBucket: 'socchat-d20de.firebasestorage.app',
  );
}
